- hosts: terraform-ansible
  tasks: 
  - name: Install Python 3 and Virtualenv
    apt:
      pkg:
      - python3
      - virtualenv
      update_cache: yes
    become: yes

  - name: Install Django and Django Rest
    pip:
      virtualenv: /home/ubuntu/tcc/venv
      name:
        - django
        - djangorestframework