- hosts: terraform-ansible
  tasks: 

  - name: Install Python 3 and Virtualenv
    apt:
      pkg:
      - python3
      - virtualenv
      update_cache: yes
    become: yes

  - name: Install Django and Django Rest
    pip:
      virtualenv: /home/ubuntu/tcc/venv
      name:
        - django
        - djangorestframework

  - name: Chek if the project alredy exists
    stat:
      path: /home/ubuntu/tcc/setup/settings.py
    register: project   

  - name: Init project
    shell: '. /home/ubuntu/tcc/venv/bin/activate;
            django-admin startproject setup /home/ubuntu/tcc/;'
    when: not project.stat.exists

  - name: Alter hosts of settings
    lineinfile: 
      path: /home/ubuntu/tcc/setup/settings.py
      regexp: 'ALLOWED_HOSTS'
      line: "ALLOWED_HOSTS = ['*']"
      backrefs: yes

  - name: Run Server
    shell: 'cd ~/tcc; 
            . venv/bin/activate; 
            nohup python manage.py runserver 0.0.0.0:8000 &'
